### ISSUE TITLE
训练出错，ImportError: cannot import name '_DataLoaderIter'

### ISSUE THREAD

**Issue by zyf1040895256** [LongguangWang/DASR#22]
感谢您的工作，我有一个问题。当我用DF2K训练时，发现报错信息：

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "/home/XXXX/F/XXX/DASR/data/__init__.py", line 2, in <module>
    from dataloader import MSDataLoader
  File "/home/XXXX/F/XXX/DASR/dataloader.py", line 12, in <module>
    from torch.utils.data.dataloader import _DataLoaderIter
ImportError: cannot import name '_DataLoaderIter'

我的环境是：

torch                  1.1.0               
能解决下吗？

**Comment by LongguangWang** [comment]
Hi @zyf1040895256, 感谢对我们工作的关注。
首先，请再次确认下运行DASR代码时使用的环境是不是pytorch 1.1.0。在1.1.0版本应该不会出现_DataLoaderIter载入错误的。
其次，可以尝试将_DataLoaderIter类([连接](https://github.com/pytorch/pytorch/blob/v1.1.0/torch/utils/data/dataloader.py#L199))复制到你的torch.utils.data.dataloader.py中，应该也可以解决这个问题。
另外，也可以参考这个[回答](https://github.com/HolmesShuan/OISR-PyTorch/issues/6#issuecomment-615517353)将DASR中数据读取部分的代码替换为EDSR 1.2.0版本中的数据读取代码。
