### ISSUE TITLE
训练时出现一个错误AssertionError: Invalid device id

### ISSUE THREAD

**Issue by 15937612927** [LongguangWang/DASR#43]
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    model = model.Model(args, checkpoint)
  File "C:\Users\Luffy\Desktop\DASR-main\model\__init__.py", line 29, in __init__
    self.model = nn.DataParallel(self.model, range(args.n_GPUs))
  File "C:\Users\Luffy\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 142, in __init__
    _check_balance(self.device_ids)
  File "C:\Users\Luffy\Anaconda3\lib\site-packages\torch\nn\parallel\data_parallel.py", line 23, in _check_balance
    dev_props = _get_devices_properties(device_ids)
  File "C:\Users\Luffy\Anaconda3\lib\site-packages\torch\_utils.py", line 455, in _get_devices_properties
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "C:\Users\Luffy\Anaconda3\lib\site-packages\torch\_utils.py", line 455, in <listcomp>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "C:\Users\Luffy\Anaconda3\lib\site-packages\torch\_utils.py", line 438, in _get_device_attr
    return get_member(torch.cuda)
  File "C:\Users\Luffy\Anaconda3\lib\site-packages\torch\_utils.py", line 455, in <lambda>
    return [_get_device_attr(lambda m: m.get_device_properties(i)) for i in device_ids]
  File "C:\Users\Luffy\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 312, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
请问是GPU设置的问题吗？

**Comment by LongguangWang** [comment]
Hi @15937612927, `option.py`中的`n_GPUs`需要与实际电脑中的显卡数量匹配。

**Comment by 15937612927** [comment]
谢谢回答，又出现下面问题请问是怎么回事
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    import data
  File "C:\Users\Luffy\Desktop\DASR-main\data\__init__.py", line 2, in <module>
    from dataloader import MSDataLoader
  File "C:\Users\Luffy\Desktop\DASR-main\dataloader.py", line 11, in <module>
    from torch.utils.data.dataloader import DataLoader
  File "C:\Users\Luffy\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\__init__.py", line 4, in <module>
    from .dataloader import dataLoader  # noqa: F401
ImportError: cannot import name 'dataLoader'
